travis:
  secure:
    BINSTAR_TOKEN: VfMgeVAuMJl4AUqr4PNkT9p9sw6kzzW27uGTuO7ZYRReyIhC9Yy5nXXC2Ggyq8MkIcBAxSPCOw8QohdOjEa8oklVbpPkSue3WyoztYhRhOuIR54HLDp/I9MoL6+ntfe3n70kiMX2efz0gfmWaSYpyNvV2eEh0bCkpStEpZQZTGgwPBbJP/ufbchPxr2Bg73hfWhFwSsdw2wxgEmrKQ+V6oq6oVgMWkky/MTqkQSCb4B4J8ho8HlSkVOkWtqh3NSvhzidRa2dhJVrccn0CDCk8Cbctj1+i37fef22ZnMKP+32xvFvtMNGN1nS6Yx2Cx8SJGBAggVPkzmPy1psA6n2LVQRoNBToBq0BylCqe7IbHKBTVhWx9GNNQWDgsp7H4B3nqCwcQ1ifKU5imZZdSdO5WkmVuxO45Y5f9vwg2w3quh9DHpbQz8zrdcem1w5Ny3DlyNYgXQv8dTpPuGuld6sJWLZUWGtcXLuxcg4sCmesyQ2k468eBwwNpiczVogaF9f405AcsEsUbfFVKwbVAETkRu2Th31Yr71ZYzBPRqMberCgD0ZBWCmH2dpEqb8huuvtlKxadRAg44lyJAFNOSK2WrMNLXMusjYnh63sKUYS+A6rEnfnhXrWh3QfbpJls66I9WolWa/pi12973gAyaXcacbL0FO3UQ6bUjnGOQf9OM=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
